/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_sai.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define SAI1_PERIPHERAL SAI1
/* SAI1 interrupt vector ID (number). */
#define SAI1_IRQN SAI1_IRQn
/* SAI1 interrupt handler identifier. */
#define SAI1_IRQHANDLER SAI1_IRQHandler
/* Leader clock source frequency used for calculating the leader clock divider, not available on all devices. */
#define SAI1_MCLK_SOURCE_CLOCK_HZ 12288000UL
/* Leader clock value set by the user to the Leader clock frequency item. */
#define SAI1_USER_MCLK_HZ 12288000UL
/* Bit clock source frequency used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_BCLK_SOURCE_CLOCK_HZ 48000000UL
/* Bit clock source frequency used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI1_RX_BCLK_SOURCE_CLOCK_HZ 48000000UL
/* Sample rate used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_SAMPLE_RATE 48000UL
/* Sample rate used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI1_RX_SAMPLE_RATE 48000UL
/* Word width used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_WORD_WIDTH 32U
/* Word width used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI1_RX_WORD_WIDTH 32U
/* Number of words within frame used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_WORDS_PER_FRAME 2U
/* Number of words within frame used for calculating the bit clock divider in the RxSetBitClockRate function. */
#define SAI1_RX_WORDS_PER_FRAME 2U
/* BOARD_InitPeripherals defines for LP_FLEXCOMM2 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM2_PERIPHERAL LPI2C2
/* Definition of peripheral base address */
#define LP_FLEXCOMM2_PERIPHERAL_BASE LPI2C2_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM2_CLOCK_SOURCE 12000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern sai_transceiver_t SAI1_Tx_config;
extern sai_transceiver_t SAI1_Rx_config;
extern const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
